name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write

    steps:
      - name: Login to GitHub
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: build+push
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: ghcr.io/raulcabello/cosign-keyless-test:0.1
